package machines;

public enum States {
    WORD_CLASS_MATCH,
    WORD_CLASS_MATCH_ANYWHERE,
    WORD_CLASS_MATCHED,

    DIGIT_MATCH,
    DIGIT_MATCH_ANYWHERE,
    DIGIT_MATCHED,

    LITERAL_MATCH,
    LITERAL_MATCH_ANYWHERE,
    LITERAL_MATCHED,
}
