package machines;

// TODO: all \w+_NOT_MATCHED states can be collapsed to single NOT_MATCHED state.
public enum States {
    SART_STATE, // Just some random state
    WORD_CLASS_MATCH_NEXT,
    WORD_CLASS_MATCH_ANYWHERE,
    WORD_CLASS_MATCHED,
    WORD_CLASS_NOT_MATCHED,

    DIGIT_MATCH_NEXT,
    DIGIT_MATCH_ANYWHERE,
    DIGIT_MATCHED,
    DIGIT_NOT_MATCHED,

    LITERAL_MATCH_NEXT,
    LITERAL_MATCH_ANYWHERE,
    LITERAL_MATCHED,
    LITERAL_NOT_MATCHED,

    POS_GROUP_MATCH_NEXT,
    POS_GROUP_MATCH_ANYWHERE,
    POS_GROUP_NOT_MATCHED,
    POS_GROUP_MATCHED,

    NEG_GROUP_MATCH_NEXT,
    NEG_GROUP_MATCH_ANYWHERE,
    NEG_GROUP_NOT_MATCHED,
    NEG_GROUP_MATCHED,
}
